import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { BirthdayCake } from "../components/BirthdayCake";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Birthday Wishes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Happy Birthday!</h1>
        <div className={styles.cakeContainer}>
          <BirthdayCake />
        </div>
        <button className={styles.button}>MAKE A WISH!</button>
      </main>
    </div>
  );
};

export default Home;
